version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: 'development'
    ports:
      - ${SERVER_PORT}:3001
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - dev-db
  dev-db:
    image: postgres:13.2
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_SCHEMA: ${DB_SCHEMA}
    networks:
      - db-network
  test-db:
    image: postgres:13.2
    ports:
      - ${TEST_DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
      DB_SCHEMA: ${TEST_DB_SCHEMA}
    networks:
      - db-network

networks:
  db-network:


